name: 🔄 Sync from template

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 2"  # Dimarts 05:00 UTC

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: template-sync
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      TEMPLATE_REPO: "oriolcortes/template-node-ts"   # ← el teu template
      TEMPLATE_BRANCH: "main"
      PR_TITLE: "chore(template): sync from template"
      PR_LABELS: "template-sync,maintenance"
      BRANCH_PREFIX: "chore/template-sync"

    steps:
      - name: Checkout (target repo) SENSE credencials
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # <- clau

      - name: Check PAT presence
        run: |
          if [ -z "${{ secrets.TEMPLATE_SYNC_TOKEN }}" ]; then
            echo "PAT secret is MISSING"; exit 1;
          else
            echo "PAT secret is PRESENT";
          fi

      - name: Forçar git a usar el PAT per a github.com
        run: |
          git config --global url."https://x-access-token:${{ secrets.TEMPLATE_SYNC_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Sync from template (PAT al target)
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          # Llegeix de l’origen públic
          source_gh_token: ${{ secrets.GITHUB_TOKEN }}
          # Escriu al destí (incloent .github/workflows/**) amb PAT
          target_gh_token: ${{ secrets.TEMPLATE_SYNC_TOKEN }}

          source_repo_path: ${{ env.TEMPLATE_REPO }}
          upstream_branch: ${{ env.TEMPLATE_BRANCH }}
          pr_title: ${{ env.PR_TITLE }}
          pr_labels: ${{ env.PR_LABELS }}
          pr_branch_name_prefix: ${{ env.BRANCH_PREFIX }}
          pr_body: |
            This is an automated pull request to synchronize from the template.
            - Source: ${{ env.TEMPLATE_REPO }}
            - Branch: ${{ env.TEMPLATE_BRANCH }}
