name: 🔄 Sync from template

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 5"  # Divendres 05:00 UTC

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: template-sync
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      # 👇 POSA AQUÍ EL TEU TEMPLATE PÚBLIC CORRECTE (owner/repo)
      TEMPLATE_REPO: "oriolcortes/template-base"
      TEMPLATE_BRANCH: "main"

      PR_TITLE: "chore(template): sync from template"
      PR_LABELS: "template-sync,maintenance"
      BRANCH_PREFIX: "chore/template-sync"

    steps:
      - name: Checkout (target repo)
        uses: actions/checkout@v4

      - name: Sync from template
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          # ✅ usa els nous inputs; el template és públic, així que el GITHUB_TOKEN ja val
          source_gh_token: ${{ secrets.GITHUB_TOKEN }}
          target_gh_token: ${{ secrets.GITHUB_TOKEN }}

          source_repo_path: ${{ env.TEMPLATE_REPO }}
          upstream_branch: ${{ env.TEMPLATE_BRANCH }}

          pr_title: ${{ env.PR_TITLE }}
          pr_labels: ${{ env.PR_LABELS }}
          pr_branch_name_prefix: ${{ env.BRANCH_PREFIX }}
          pr_body: |
            This is an automated pull request to synchronize from the template.
            - Source: ${{ env.TEMPLATE_REPO }}
            - Branch: ${{ env.TEMPLATE_BRANCH }}

      - name: Done
        run: echo "Opened/updated PR if changes exist."
